### ISSUE TITLE
ERROR: ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by laimonassutkus** [OvidijusParsiunas/active-table#39]
Using ActiveTable on React project. Sample code:

```
      <ActiveTable
        ref={activeTableRef}
        tableStyle={{
          "width": "100%"
        }}
        data={[
          ['Planet', 'Diameter', 'Mass'],
          ['Earth', 1, 1],
          ['Mars', 1, 1],
        ]}
      />
```

Resizing window quickly:

```
Uncaught runtime errors:
×
ERROR
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3001/static/js/bundle.js:38010:58)
    at http://localhost:3001/static/js/bundle.js:38029:7
```

**Comment by eviltik** [comment]
Are you using webpack ?

If yes, you can see that this message will not appear in your production dist. 

So 

1. You can hide error message in webpack (devserver) using this 

```
 devServer: {
    //so that dist folder is served on development server
    //contentBase: './dist',
    client: {
      logging: 'verbose',
      progress:false,
      overlay: {
        runtimeErrors: (error) => {
          const ignoreErrors = [
            "ResizeObserver loop limit exceeded",
            "ResizeObserver loop completed with undelivered notifications.",
          ];
          if (ignoreErrors.includes(error.message)) {
            return false;
          }
          return true;
        }
      },
    }
}
```

2. You can go deeper in active-table code to see what is the "problem". Good luck.
